# Site settings
title: Developers PayU
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown

collections:
 en:
  output: true
#  permalink: /my_collection/:path/
 es:
  output: true
  layout: default.html
#  permalink: /my_collection/:path/
 pt:
  output: true
#  permalink: /my_collection/:path/


defaults:
  -
    scope:
      path: ""
      type: "es" # a collection in your site, in plural form
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "en" # a collection in your site, in plural form
    values:
      layout: "default_en"	  
  -
    scope:
      path: ""
      type: "pt" # a collection in your site, in plural form
    values:
      layout: "default_pt"	  