# Site settings
title: Developers PayU
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.payulatam.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll


# Build settings
markdown: kramdown

collections:
 en:
  output: true
#  permalink: /my_collection/:path/
 es:
  output: true
  layout: default
#  permalink: /my_collection/:path/
 pt:
  output: true
#  permalink: /my_collection/:path/


defaults:

#categorias español  
  -
    scope:
      path: ""
    values:
      layout: default	
  -
    scope:
      path: "es/api"
    values:
      category: "api"	  
  -
    scope:
      path: "es/sdk"
    values:
      category: "sdk"
  -
    scope:
      path: "es/web_checkout"
    values:
      category: "web_checkout"
  -
    scope:
      path: "es/solutions"
    values:
      category: "solutions"	  
  -
    scope:
      path: "es/administrative_module"
    values:
      category: "solutions"	
#categorias ingles  
  -
    scope:
      path: "en/api"
    values:
      category: "api"	  
  -
    scope:
      path: "en/sdk"
    values:
      category: "sdk"
  -
    scope:
      path: "en/web_checkout"
    values:
      category: "web_checkout"
  -
    scope:
      path: "en/solutions"
    values:
      category: "solutions"	  
  -
    scope:
      path: "en/administrative_module"
    values:
      category: "solutions"  
#categorias portugues  
  -
    scope:
      path: "pt/api"
    values:
      category: "api"	  
  -
    scope:
      path: "pt/sdk"
    values:
      category: "sdk"
  -
    scope:
      path: "pt/web_checkout"
    values:
      category: "web_checkout"
  -
    scope:
      path: "pt/solutions"
    values:
      category: "solutions"	  
  -
    scope:
      path: "pt/administrative_module"
    values:
      category: "solutions"  

  